### ISSUE TITLE
Error when serializing struct with string element

### ISSUE THREAD

**Issue by amunhoz** [niXman/yas#81]
Get this error in the code: 

```
/home/ivuser/.conan/data/yas/7.0.5/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/yas/json_oarchive.hpp:88:16: error: incomplete type ‘yas::detail::serializer<(yas::detail::type_prop)4, (yas::detail::ser_case)4, 4, std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > >’ used in nested name specifier
         return serializer<
                ~~~~~~~~~~~
              detail::type_properties<T>::value
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             ,detail::serialization_method<T, this_type>::value
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             ,F
             ~~  
             ,T
             ~~  
         >::save(*this, v);
         ~~~~~~~^~~~~~~~~~
```

code:
```
struct msgHeadery
{
    char type = '#'; 
    std::string channel = "#";
    std::string sub_id;
    map<string, string> info;
    //char msgtype = 'p'; //p=publishall o=publishonce r=request e=requestonce //problem with local publish
    
    //optional
    bool encrypted = false; 
    uint32_t iv1 = 0;
    uint32_t iv2 = 0;   
    template<typename Ar>
    void serialize(Ar &ar) {
        ar & YAS_OBJECT(nullptr /* reserved */, type, channel, info, encrypted,iv1, iv2);
    }
};

constexpr std::size_t flags = yas::mem|yas::json;
msgHeadery lala;
yas::shared_buffer buf = yas::save<flags>(lala);
```

When i remove the strings elements (type, channel and info) it compiles fine with gcc  7.5.0 + std=c++17

**Comment by niXman** [comment]
Hi,

please provide complete example.

**Comment by niXman** [comment]
I don’t know what your problems are but I compiled this code without a single error...

closed.
